/* VIEW는 가상의 테이블 : 테이블처럼 사용할 수 있음 
   VIEW의 사용목적
	1. 편리성 : 복잡한 명령이나 수식을 간결하게 사용할 수 있다.
	2. 보안성 : 중요 데이터를 외부로부터 감출 수 있다. 
	일반적으로 조회 용도로 사용된다
   VIEW 의 실제 형태: 내부에 실행할 수 있는 SQL문을 저장
   VIEW를 사용하려면 권한을 부여받아야한다.
   
*/

-- 

-- 사원테이블에서 남자직원만 조회하는 뷰 만들기

CREATE OR REPLACE VIEW SAWON_VIEW_GENDER_MALE
AS SELECT * FROM SAWON WHERE SASEX = '남자'

-- 뷰 사용하기
SELECT * FROM SAWON_VIEW_GENDER_MALE

-- 사원테이블에서 입사년도/입사월/입사일을 구하는 뷰 만들기
CREATE OR REPLACE VIEW SAWONVIEW
AS
	SELECT 
		SABUN, SANAME, SASEX, DEPTNO, SAJOB, SAHIRE, SAMGR, SAPAY,
		TO_NUMBER(TO_CHAR(SAHIRE,'YYYY')) AS HIRED_YEAR,
		TO_NUMBER(TO_CHAR(SAHIRE,'MM')) AS HIRED_MONTH,
		TO_NUMBER(TO_CHAR(SAHIRE,'DD')) AS HIRED_DAY
FROM SAWON

SELECT 
	HIRED_YEAR,
	COUNT(*)
FROM SAWONVIEW
GROUP BY HIRED_YEAR
ORDER BY HIRED_YEAR

-- 기존 뷰에 입사 계절 추가하기
CREATE OR REPLACE VIEW SAWON_SEASONVIEW
AS(
	SELECT 
	SV.*,
	CASE FLOOR(HIRED_MONTH/3)
	WHEN 1 THEN '봄'
	WHEN 2 THEN '여름'
	WHEN 3 THEN '가을'
	ELSE '겨울'
	END AS HIRED_SEASON
	FROM (SELECT * FROM SAWONVIEW) SV -- INLINE VIEW (구문이 끝나면 소멸되는 일시적인 VIEW) 
)

SELECT * FROM SAWON_SEASONVIEW 

-- 사원테이블에서 입사계절별 인원수를 구하기
SELECT
HIRED_SEASON,
COUNT(*) AS 인원
FROM SAWON_SEASONVIEW
GROUP BY HIRED_SEASON

-- 고객테이블
CREATE OR REPLACE VIEW GOGEKVIEW
AS
	SELECT 
	GOBUN, 
	GONAME, 
	GOADDR,
	SUBSTR(GOJUMIN,1,7)|| '*******' AS GOJUMIN,
	(
	TO_NUMBER(SUBSTR(GOJUMIN,1,2)) +
		CASE 
		WHEN TO_NUMBER(SUBSTR(GOJUMIN,8,1)) IN(1,2,5,6) THEN 1900
		WHEN TO_NUMBER(SUBSTR(GOJUMIN,8,1)) IN(3,4,7,8) THEN 2000
		ELSE 1800
		END
	) AS BIRTHYEAR,
	GODAM
FROM GOGEK
ORDER BY GOBUN
SELECT * FROM GOGEKVIEW

-- CONNECTIONS PROFILE NAME 을 ORACLE_SYSTEM으로 변경하고 작업해야함
-- SYSTEM 계정으로부터 TEST7 계정을 생성한다.
CREATE USER TEST7 IDENTIFIED BY TEST7
GRANT CONNECT TO TEST7

-- GOGEKVIEW에 대한 사용권한(SELECT)을 TEST7에게 부여하기
-- 해당개체에 대한 권한은 소유주(DBO)가 부여한다.
GRANT SELECT ON GOGEKVIEW TO TEST7

SELECT * FROM test.GOGEKVIEW







